[package]
name = "gomoku"
version = "1.0.0"
authors = ["Maneren <maneren731@gmail.com>"]
edition = "2021"

[dependencies]
clap = "2"
num_cpus = "1"
regex = "1"
text_io = "0"
gomoku_lib = { path = "./gomoku" }
