[package]
name = "gomoku"
version = "0.1.0"
authors = ["Maneren <49210777+Maneren@users.noreply.github.com>"]
edition = "2018"

[dependencies]
clap = "2"
num_cpus = "1"
rand = "0"
text_io = "0"
threadpool = "1"
