[package]
name = "gomoku"
version = "1.0.0"
authors = ["Maneren <maneren731@gmail.com>"]
edition = "2021"

[dependencies]
clap = "3.2.23"
num_cpus = "1.15.0"
text_io = "0.1.12"
gomoku_lib = { path = "./gomoku" }
