[package]
name = "gomoku"
version = "7.1.0"
authors = ["Maneren <maneren731@gmail.com>"]
edition = "2024"

[workspace]

[profile.release-debug]
inherits = "release"
strip = false
debug = true

[profile.release]
strip = true
lto = true
codegen-units = 1

[dependencies]
clap = "4.6.6"
num_cpus = "1.17.0"
text_io = "0.1.13"
gomoku_lib = { path = "./gomoku", features = ["mimalloc", "fen"] }
