[package]
name = "gomoku_lib"
version = "6.1.1"
authors = ["Maneren <maneren731@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["lib"]

[features]
jemalloc = []

[dependencies]
regex = "1.7.1"
rayon = "1.6.1"
once_cell = "1.17.0"
jemallocator = "0.5.0"
