[package]
name = "gomoku_lib"
version = "7.1.0"
authors = ["Maneren <maneren731@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["lib"]

[features]
jemalloc = ["jemallocator"]
fen = ["regex"]

[dependencies]
regex = { version = "1.11.1", optional = true }
rayon = "1.10.0"
scc = "2.3.4"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = { version = "0.5.4", optional = true }
