[package]
name = "gomoku_lib"
version = "7.1.0"
authors = ["Maneren <maneren731@gmail.com>"]
edition = "2024"

[lib]
crate-type = ["lib"]

[features]
mimalloc = ["dep:mimalloc"]
fen = ["regex"]

[dependencies]
mimalloc = { version = "0.1.52", optional = true }
regex = { version = "1.13.1", optional = true }
rayon = "1.12.0"
